# Generated by Django 5.0.2 on 2024-03-27 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0002_alter_employee_department"),
    ]

    operations = [
        migrations.CreateModel(
            name="Date",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date", models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="ScheduleHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Shift", models.IntegerField()),
                (
                    "Date",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="apps.date"
                    ),
                ),
                ("EmployeeList", models.ManyToManyField(to="apps.employee")),
            ],
        ),
    ]
