# Generated by Django 5.0.2 on 2024-03-27 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0003_date_schedulehistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedulehistory",
            name="Department",
            field=models.CharField(default=1980, max_length=50),
            preserve_default=False,
        ),
    ]
