# Generated by Django 5.0.2 on 2024-03-28 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0004_schedulehistory_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedulehistory",
            name="SubEmployeeList",
            field=models.ManyToManyField(
                related_name="sub_schedule_history", to="apps.employee"
            ),
        ),
        migrations.AlterField(
            model_name="schedulehistory",
            name="EmployeeList",
            field=models.ManyToManyField(
                related_name="schedule_history", to="apps.employee"
            ),
        ),
    ]
