# Generated by Django 5.0.2 on 2024-04-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0005_schedulehistory_subemployeelist_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InHoliday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("EmployeeID", models.IntegerField()),
                ("StartDate", models.DateField()),
                ("EndDate", models.DateField()),
            ],
            options={
                "unique_together": {("EmployeeID", "StartDate")},
            },
        ),
    ]
