# Generated by Django 5.0.2 on 2024-04-09 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0006_inholiday"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="inholiday",
            unique_together=set(),
        ),
    ]
